use_frameworks!

platform :ios, '10.0'

target 'MJExtensions_Example' do
  pod 'SnapKit'
  pod 'MJExtensions', :path => '../'

  target 'MJExtensions_Tests' do
    inherit! :search_paths

    
  end
end
